### ISSUE TITLE
Build Failure in mcp-server due to Missing Dependencies and Type Definitions

### ISSUE THREAD

**Issue by alexqem** [eyalzh/browser-control-mcp#17]
The npm run build command is currently failing, specifically within the mcp-server project. The build log indicates multiple TypeScript errors (TS2307, TS2580, TS2503, TS7006, TS7031) related to missing module installations and type declarations.

Key issues observed:

'tsc' is not recognized (initially, now resolved by npm install for typescript in mcp-server)

Cannot find module 'ws', '@modelcontextprotocol/sdk/server/...', 'zod', 'dayjs', etc.

Cannot find module 'path', 'fs/promises', 'crypto', 'net' (indicating missing @types/node).

Cannot find name 'process' and Cannot find namespace 'NodeJS' (also indicating missing @types/node).

Parameter '...' implicitly has an 'any' type errors, likely stemming from the above missing type definitions.

Steps to Reproduce:

Clone the repository.

Navigate to the project root.

Run npm install (to install root dependencies).

Run npm run build.

Running on Windows

**Comment by ajh216** [comment]
@alexqem originally I was running into this issue as well; however after troubleshooting I realized I was running an older version of node which may have been causing the issues. Having since upgraded to v22.17 seemed to resolve the issue and I was able to build fine. 

Passed that hurdle but now I am having issues generating the shared secret... 

hope the above helps.
